### ISSUE TITLE
MH4U Crash

### ISSUE THREAD

**Issue by stripeddinos** [mikewii/Luma3DS-plugin#31]
When preforming the long sword spirit combo, at the end of it the game crashes. I've used it with the most recent update of the plugin so yeah, it was also in the previous version as well. Also github is not allowing me to add the  crash dump file, so if there's any way i can share it, please inform me.
Edit: I've added the file to the gbatemp thread.

**Comment by mikewii** [comment]
provide crash dump

**Comment by stripeddinos** [comment]
Crash dump was provided in this post 
https://gbatemp.net/threads/monster-hunter-4u-xx-qol-codes.532190/page-13#post-9272869

**Comment by egar3427** [comment]
This is the crash dump.
[crash_dump_00000031.zip](https://github.com/mikewii/Luma3DS-plugin/files/5639356/crash_dump_00000031.zip)
I've tried reverting to previous version and it still crashing.

**Comment by mikewii** [comment]
fixed https://github.com/mikewii/Luma3DS-plugin/releases/tag/r1.0.9.4
