### ISSUE TITLE
"Error writing settings to file"

### ISSUE THREAD

**Issue by dlzaxo** [mikewii/Luma3DS-plugin#38]
![2021-03-12_21-24-56 486_top](https://user-images.githubusercontent.com/70489564/111020257-5ed17980-8379-11eb-8ca1-548602d860bb.jpg)

Three questions:
Can you upload a settings file? 
Can you manually edit a settings file? 
Where would this file be located on an SD card?

Thank you.

**Comment by mikewii** [comment]
check if you have path /luma/plugins/ActionReplay

**Comment by dlzaxo** [comment]
I didn't at the time, but I have just created the path. I will give it a shot now.

Should I have something in the folder? Or do I just need the path?

**Comment by mikewii** [comment]
will fix this issue in upcoming release

**Comment by mikewii** [comment]
https://github.com/mikewii/Luma3DS-plugin/releases/tag/1.0.10
