### ISSUE TITLE
[Feature Request] Release source code

### ISSUE THREAD

**Issue by MisterPrintf** [mikewii/Luma3DS-plugin#4]
I'd really like to be able to tweak things to my own personal needs; unfortunately this is impossible right now.
Even in the releases page, the only thing inside of Source Code.zip is the Readme.txt.

**Comment by MisterPrintf** [comment]
Also, more information as regards which version of Luma3DS this is forked from would be nice.

**Comment by mikewii** [comment]
Plugin sources stay closed.
Luma https://github.com/mikewii/Luma3DS
