### ISSUE TITLE
mhxx crashes on start-up with plugin enabled

### ISSUE THREAD

**Issue by skullx0** [mikewii/Luma3DS-plugin#45]
I have put the plugin in luma/plugins as well as the root. Just rename the file extension to .dmp (github wouldn't let me upload it)
[crash_dump_00000026.txt](https://github.com/mikewii/Luma3DS-plugin/files/7147992/crash_dump_00000026.txt)

**Comment by mikewii** [comment]
go to utils->debug info and show me commit hash

**Comment by skullx0** [comment]
How do i do that, I am fairly new to this.

**Comment by mikewii** [comment]
run any other game and check commit hash in plugin

**Comment by skullx0** [comment]
the commit hash is 0c109ba1

**Comment by mikewii** [comment]
issue happens on loading AR cheats file, can you send it to me?

**Comment by mikewii** [comment]
actually update plugin to latest release, then see if issue stay

**Comment by skullx0** [comment]
I already have the latest release from 21st of May, and where would the AR cheats file be? I'm assuming somewhere in the Luma folder.

**Comment by mikewii** [comment]
yeah was confused a lot with commit and code dump, it doesnt match...probably because i did silent changes to fix some critical issue on release.
i'll clean code and upload plugin today with new fixes, try it out and see if your issue still exist

**Comment by mikewii** [comment]
cant test it cuz my 3ds broke and new one arrive in like 1month, but this might fix your issue, if not post new crash report
https://github.com/mikewii/Luma3DS-plugin/releases/tag/r1.0.12

**Comment by mikewii** [comment]
well i guess unknown issue fixed itself
