### ISSUE TITLE
MHXX certain AR codes don’t work

### ISSUE THREAD

**Issue by yaboifuso** [mikewii/Luma3DS-plugin#5]
Running v1.0.6 of the plugin, and v1.4 of the game with Crosshex’s v2 English patch (also tested with dasding’s v5 English patch) most of the 1.4 codes from Vermil’s modded moveset codelist don’t function. Mainly tested with charge blade bonus (makes the charge ‘A’ sword swipe attack almost instant and fully charged) but also the bow, switch axe, mh4u charge blade v3 and hammer with no differences. All of these codes currently work fine with the blank CTRplugin framework AR system.

Also codes for FOV (v1.4) fail to work as well, tested with increments of 5 ranging from 45-75.

**Comment by yaboifuso** [comment]
To add - the codes used besides the mh4u charge blade v3 are the 1.4 provided by yourself in Vermil’s monster size mod thread on gbatemp - same with the FOV codes. Just to clarify if the codes are broken or not.

**Comment by mikewii** [comment]
There was problem with AR codes not looping.
Fixed https://github.com/mikewii/Luma3DS-plugin/releases/tag/r16fix
