### ISSUE TITLE
Add Smoke bomb timer

### ISSUE THREAD

**Issue by Vitkarus** [mikewii/Luma3DS-plugin#6]
As we know Smoke bomb work for 1 minute, so maybe it would be useful to create timer, that count from 60 to 0, and goes back to 60, when player press Y on Smoke bomb in his inventory. But in this case timer would only work for player's bombs and will not trigger by bombs from another hunters in multiplayer. Maybe it can be somehow synchronized.

**Comment by mikewii** [comment]
https://github.com/mikewii/Luma3DS-plugin/releases/tag/r17
